### ISSUE TITLE
Doesn't support multiple configs (no error)

### ISSUE THREAD

**Issue by AshtonRoute** [zinserjan/mocha-webpack#109]
I don't know if this module should support multiple configs, but there is another bug with error.

```javascript
import config1 from './foo.config';
import config2 from './bar.config';

export default [
  config1,
  config2,
];
```

```javascript
Error
    at webpack (C:\Projects\clicker-api\node_modules\webpack\lib\webpack.js:19:9)
    at createCompiler (C:\Projects\clicker-api\node_modules\mocha-webpack\lib\webpack\compiler\createCompiler.js:18:40)
    at TestRunner.<anonymous> (C:\Projects\clicker-api\node_modules\mocha-webpack\lib\runner\TestRunner.js:163:51)
    at eval (eval at processIncludes (C:\Projects\clicker-api\node_modules\nodent-runtime\runtime.js:36:12), <anonymous>:3:4642)

```

If you track it down it's a ```WebpackOptionsValidationError```

```javascript
function createCompiler(webpackConfig) {
  console.log(webpackConfig);
  try{

  var compiler = (0, _webpack2.default)(webpackConfig);
  }
  catch(err){
    console.log(err);
  }

  return compiler;
}
```

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.\n - configuration has an unknown property \'1\'.
```

Ofc, as a workaround you can run each config separately.
```
--webpack-config foo.config.js
```

**Comment by zinserjan** [comment]
Multi config isn't supported and planned. But there is a open task for this to give a good error (see open tasks in #70)
