### ISSUE TITLE
Different behavior calling mocha-webpack as an npm script

### ISSUE THREAD

**Issue by tugberkugurlu** [zinserjan/mocha-webpack#122]
I am running this command and it all works as expected, running my tests nicely:

```bash
node_modules/.bin/mocha-webpack 'src/**/*.test.js' --webpack-config webpack.config.test.js
```

I also have the below npm script command configured:

```json
  "scripts": {
    "test": "mocha-webpack 'src/**/*.test.js' --webpack-config webpack.config.test.js"
  }
```

which is essentially the same but when I run `npm run test`, I get the below output indicating that it has run none of the tests:

```
> mocha-webpack 'src/**/*.test.js' --webpack-config webpack.config.test.js

 WEBPACK  Compiling...

 WEBPACK  Compiled successfully in 41ms

 MOCHA  Testing...



  0 passing (0ms)

 MOCHA  Tests completed successfully
```

Any idea what is going wrong? Could it be a path resolution issue? Also, is there a verbose logging option for `mocha-webpack` CLI?

**Comment by zinserjan** [comment]
Can you try the following?

```
  "scripts": {
    "test": "mocha-webpack \"src/**/*.test.js\" --webpack-config webpack.config.test.js"
  }
```

> Also, is there a verbose logging option for mocha-webpack CLI?

Unfortunately not, but it's planned.

**Comment by tugberkugurlu** [comment]
> Can you try the following?
> 
>   "scripts": {
>     "test": "mocha-webpack \"src/**/*.test.js\" --webpack-config webpack.config.test.js"
>   }

This was what I had tried the first. Tried it again and getting this:

```
> foo-web-client@0.0.0 test D:\dev\foo\foobar.foo.Client.Web
> mocha-webpack "src/**/*.test.js" --webpack-config webpack.config.test.js

 WEBPACK  Compiling...

 WEBPACK  Compiled successfully in 69ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object._module2.default._extensions.(anonymous function) [as .js] (D:\Dev\foo\foobar.foo.Client.Web\node_modules\mocha-webpack\lib\util\registerRequireHook.js:145:12)
    at Module.load (module.js:343:32)
```

**Comment by tugberkugurlu** [comment]
> Unfortunately not, but it's planned.

This is nice, thanks!

**Comment by tugberkugurlu** [comment]
I have put the below script inside `run-tests` file:

```bash
#!/bin/sh

./node_modules/.bin/mocha-webpack "src/**/*.test.js" --webpack-config webpack.config.test.js
```

which made it work. So, it seems like it definitely needs double quotes around it but for some reason, npm script cannot pass them correctly it seems.

**Comment by tugberkugurlu** [comment]
`cmd` file on Windows also works:

```
node_modules/.bin/mocha-webpack "src/**/*.test.js" --webpack-config webpack.config.test.js
```

I can change the npm script to be the below to run the bash script which works running under linux:

```
  "scripts": {
    "test": "bash ./run-tests"
  }
```

but this does not work under windows.

**Comment by tugberkugurlu** [comment]
I have solved my issue but I am still unclear on why it worked under some shells, not under others.

I originally had the below webpack config:

```js
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
    target: 'node',
    externals: [nodeExternals()],
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    module: {
        loaders: [
            { test: /\.jsx?$/, loaders: ['babel'], include: path.join(__dirname, 'src') },
            { test: /\.json$/, loader: 'json' },
            { test: /(\.css)$/, loaders: 'null-loader' },
            { test: /\.scss$/, loaders: 'null-loader' },
            { test: /\.less$/, loader: 'null-loader' },
            { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'null-loader' },
            { test: /\.(jpg|png|jpeg)$/, loader: 'null-loader' }
        ]
    }
};
```

Notice anything with `{ test: /\.jsx?$/, loaders: ['babel'], include: path.join(__dirname, 'src') }` line? `include: path.join(__dirname, 'src')` statement there causing my issue. Combination of removing that and following [your suggestion](https://github.com/zinserjan/mocha-webpack/issues/122#issuecomment-283102448) made it work for me 🎉

**Comment by FernandoDColon** [comment]
Try with this:

```
{ test: /\.jsx?$/, loaders: ['babel-loader'], include: path.join(__dirname, 'src') }
```

**Comment by FernandoDColon** [comment]
> I have solved my issue but I am still unclear on why it worked under some shells, not under others.
> 
> I originally had the below webpack config:
> 
> ```js
> const path = require('path');
> const nodeExternals = require('webpack-node-externals');
> 
> module.exports = {
>     target: 'node',
>     externals: [nodeExternals()],
>     resolve: {
>         extensions: ['', '.js', '.jsx']
>     },
>     module: {
>         loaders: [
>             { test: /\.jsx?$/, loaders: ['babel'], include: path.join(__dirname, 'src') },
>             { test: /\.json$/, loader: 'json' },
>             { test: /(\.css)$/, loaders: 'null-loader' },
>             { test: /\.scss$/, loaders: 'null-loader' },
>             { test: /\.less$/, loader: 'null-loader' },
>             { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'null-loader' },
>             { test: /\.(jpg|png|jpeg)$/, loader: 'null-loader' }
>         ]
>     }
> };
> ```
> 
> Notice anything with `{ test: /\.jsx?$/, loaders: ['babel'], include: path.join(__dirname, 'src') }` line? `include: path.join(__dirname, 'src')` statement there causing my issue. Combination of removing that and following [your suggestion](https://github.com/zinserjan/mocha-webpack/issues/122#issuecomment-283102448) made it work for me 🎉

Try with this:

```
{ test: /\.jsx?$/, loaders: ['babel-loader'], include: path.join(__dirname, 'src') }
```
