### ISSUE TITLE
Mocha-webpack does not work with Webpack 3

### ISSUE THREAD

**Issue by ecbrodie** [zinserjan/mocha-webpack#143]
[Webpack 3 has just been released](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b). I know that the README calls out that only Webpack up to version 2.x.x is supported. @zinserjan will you be supporting Webpack v3? Thank you.

<details>
<summary><b>Here is the error stack trace that I currently am running into:</b></summary>

```
> yarn test
yarn test v0.24.6
$ mocha-webpack --opts ./spec/mochaWebpack.opts --reporter dot 

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./c8b7eb2c5f2855ed4e862371c302c4aa-entry.js in /builds/my-app/client/.tmp/mocha-webpack
resolve file
  /builds/my-app/client/.tmp/mocha-webpack/c8b7eb2c5f2855ed4e862371c302c4aa-entry.js.js doesn't exist
  /builds/my-app/client/.tmp/mocha-webpack/c8b7eb2c5f2855ed4e862371c302c4aa-entry.js.jsx doesn't exist
resolve directory
  /builds/my-app/client/.tmp/mocha-webpack/c8b7eb2c5f2855ed4e862371c302c4aa-entry.js/package.json doesn't exist (directory description file)
  /builds/my-app/client/.tmp/mocha-webpack/c8b7eb2c5f2855ed4e862371c302c4aa-entry.js is not a directory (directory default file)
Error: Cannot find module '/builds/my-app/client/.tmp/mocha-webpack/c8b7eb2c5f2855ed4e862371c302c4aa/c8b7eb2c5f2855ed4e862371c302c4aa-output.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /builds/my-app/client/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/builds/my-app/client/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/builds/my-app/client/node_modules/mocha/lib/mocha.js:487:10)
    at /builds/my-app/client/node_modules/mocha-webpack/lib/cli/runner.js:59:11
    at Compiler.<anonymous> (/builds/my-app/client/node_modules/mocha-webpack/lib/webpack/createCompiler.js:72:7)
    at Compiler.applyPlugins (/builds/my-app/client/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.<anonymous> (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:193:12)
    at Compiler.emitRecords (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:187:11)
    at /builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/builds/my-app/client/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:267:14)
    at /builds/my-app/client/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/builds/my-app/client/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/builds/my-app/client/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/builds/my-app/client/node_modules/mocha-webpack/node_modules/webpack/lib/Compiler.js:235:20)
    at /builds/my-app/client/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.
ERROR: Job failed: exit code 1
```
</details>

**Comment by zinserjan** [comment]
Which mocha-webpack version are you using?

**Comment by ecbrodie** [comment]
@zinserjan I am using the latest version, which is `0.7.0`.

**Comment by zinserjan** [comment]
Can you try `1.0.0-beta.1`?

**Comment by ecbrodie** [comment]
Just gave it a try and it looks like I am able to run `webpack@3.0.0` when using `mocha-webpack@1.0.0-beta.1`. This allows me to close the issue.

I would like recommend that this project's README be changed to mention that this beta version exists and that it supports Webpack v3. This will help you save time from having to answer to Issues like this one, for mocha-webpack users wishing to upgrade to Webpack v3. This may become a more frequent occurrence now that Webpack v3 has recently been released.

**Comment by ecbrodie** [comment]
After upgrading to `webpack@3.0.0` and `mocha-webpack@1.0.0-beta.1`, I run into the following error:

```
 WEBPACK  Failed to compile with 1 error(s)

Error

  Entry module not found: Error: Cannot resolve 'file' or 'directory' /Users/evanbrodie/my-app/client/node_modules/mocha-webpack/lib/entry.js in /Users/evanbrodie/my-app/client

error Command failed with exit code 1.
```
