### ISSUE TITLE
Unable to lookup source

### ISSUE THREAD

**Issue by jvanbruegge** [zinserjan/mocha-webpack#170]
Hello,
I followed the guides and was able to setup coverage and mocha-webpack. But when I open the coverage (html reported) and click on the source file I want to see, i get this error:
```
Unable to lookup source: /home/jan/test/test1/node_modules/ifdef-loader/ifdef-loader.js?json={"PRODUCTION":true,"DEVELOPMENT":false}!/home/jan/test/test1/node_modules/tslint-loader/index.js!/home/jan/test/test1/src/components/counter.tsx(ENOENT: no such file or directory, open '/home/jan/test/test1/node_modules/ifdef-loader/ifdef-loader.js?json={"PRODUCTION":true,"DEVELOPMENT":false}!/home/jan/test/test1/node_modules/tslint-loader/index.js!/home/jan/test/test1/src/components/counter.tsx')
Error: Unable to lookup source: /home/jan/test/test1/node_modules/ifdef-loader/ifdef-loader.js?json={"PRODUCTION":true,"DEVELOPMENT":false}!/home/jan/test/test1/node_modules/tslint-loader/index.js!/home/jan/test/test1/src/components/counter.tsx(ENOENT: no such file or directory, open '/home/jan/test/test1/node_modules/ifdef-loader/ifdef-loader.js?json={"PRODUCTION":true,"DEVELOPMENT":false}!/home/jan/test/test1/node_modules/tslint-loader/index.js!/home/jan/test/test1/src/components/counter.tsx')
     at Context.defaultSourceLookup [as sourceFinder] (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/context.js:15:15)
     at Context.getSource (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/context.js:74:17)
     at Object.annotateSourceCode (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:175:38)
     at HtmlReport.onDetail (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:217:39)
     at Visitor.(anonymous function) [as onDetail] (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)     at ReportNode.Node.visit (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17) 
     at /home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
     at Array.forEach (native)     at visitChildren (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
     at ReportNode.Node.visit (/home/jan/test/test1/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
--
```
How can I fix that?

**Comment by jvanbruegge** [comment]
I think this is a problem of istanbul-instrumenter-loader, I opened an issue there: https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/69
