### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by neekey** [zinserjan/mocha-webpack#198]
Hi I just updated my React to 16, and mocha-webpack gave me errors:

```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
 RUNTIME EXCEPTION  Exception occurred while loading your tests

Error: react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/enzyme/build/react-compat.js:144:13)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/enzyme/build/Utils.js:65:20)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/enzyme/build/MountedTraversal.js:36:14)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/enzyme/build/ReactWrapper.js:35:25)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/enzyme/build/index.js:6:21)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at eval (webpack:///external_%22enzyme%22?:1:18)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:118:1)
    at __webpack_require__ (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:20:30)
    at eval (webpack:///./src/app/components/card/comp.Card.spec.js?:9:15)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:1089:1)
    at __webpack_require__ (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:20:30)
    at run (webpack:///./node_modules/mocha-webpack/lib/entry.js?:3:20)
    at Array.forEach (<anonymous>)
    at eval (webpack:///./node_modules/mocha-webpack/lib/entry.js?:10:24)
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:1082:1)
    at __webpack_require__ (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:20:30)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:63:18
    at Object.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/.tmp/mocha-webpack/1512532075474/bundle.js:66:10)
    at Module._compile (module.js:573:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/util/registerRequireHook.js:147:12)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha/lib/mocha.js:495:10)
    at runMocha (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/runner/TestRunner.js:249:35)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/runner/TestRunner.js:305:13
    at Compiler.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7)
    at Compiler.applyPlugins (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:998:13)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:906:16
    at MemoryFileSystem.writeFile (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:343:28)
    at require.forEach (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:349:12)
    at /Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/async/dist/async.js:3145:5)
    at emitFiles (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/webpack/lib/Compiler.js:319:21)
    at Immediate.<anonymous> (/Users/neekey/Documents/github/insiight/app.narratiive.com/node_modules/mocha-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)


```

**Comment by neekey** [comment]
Sorry, it was caused by Enzyme.
