### ISSUE TITLE
Source Maps not Working?

### ISSUE THREAD

**Issue by gsccheng** [zinserjan/mocha-webpack#210]
I'm running mocha-webpack v1.0.1 and it says that it handles source-maps automatically for you. However, I get errors like these that points to the bundle file that suggests it isn't working for me?
```
       Save button
         on mount should be disabled:
     TypeError: Cannot read property 'map' of undefined
      at VueComponent.get (.tmp/mocha-webpack/1519857347441/bundle.js:141257:56)
      at Watcher.get (.tmp/mocha-webpack/1519857347441/bundle.js:29988:25)
      at Watcher.evaluate (.tmp/mocha-webpack/1519857347441/bundle.js:30095:21)
      at VueComponent.computedGetter [as BKList] (.tmp/mocha-webpack/1519857347441/bundle.js:30389:17)
```

Here is my webpack config file. Am I doing something wrong?

```
var path = require('path')
var webpack = require('webpack')
var utils = require('./utils')
var config = require('../config')

function resolve(dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  resolve: {
    modules: [path.resolve('./src'), "node_modules"],
    extensions: ['.js', '.vue', '.json', '.ts'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src')
    }
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  plugins: [
     new webpack.DefinePlugin({
       'process.env': require('../config/test.env')
     })
   ],
  module: {
    loaders: [
      {
        test: /\.pug$/,
        loader: 'pug-loader'
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.ts$/,
        loader: "awesome-typescript-loader",
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(mp3|wav)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('audio/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      ...utils.styleLoaders({ sourceMap: true })
    ]
  },
  resolveLoader: {
    alias: {
      // necessary to to make lang="scss" work in test when using vue-loader's ?inject option 
      // see discussion at https://github.com/vuejs/vue-loader/issues/724
      'scss-loader': 'sass-loader'
    }
  }
}
```

**Comment by serut** [comment]
You should write

```
       'process.env': JSON.stringify(require('../config/test.env'))
```
We are using too Mocha webpack, here is our conf : https://github.com/RegardsOss/regards-frontend/blob/master/frontend-webapp/src/main/webapp/webpack-config-front/src/app/webpack.test.config.js

**Comment by gsccheng** [comment]
@serut Thanks for the response. When I stringify I get something like this:
```
/path/to/.tmp/mocha-webpack/1520026530408/bundle.js:28061
    {"NODE_ENV":"\"test\"", ... ,"IDLE_TIME":"\"600000\"","IDLE_POPUP_TIMEOUT":"\"60\"", "cssSourceMap":"\"true\""}.NODE_ENV !== 'production' && warn(
               ^
SyntaxError: Unexpected token :
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
```
If I include a  `devtool: 'inline-source-map',`, I get
```
/Users/gabrielcheng/Desktop/agentiq/dashboard-v1/node_modules/source-map-support/source-map-support.js:129
  while (match = re.exec(fileData)) lastMatch = match;
                    ^
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
```
However, a ` devtool: '#cheap-module-eval-source-map'` or just `devtool: 'source-map'` gives me the same output as in my original post, no errors but doesn't seem to actually map anything.

I also see that you included the snippet below as well. That too seems to have no effect.
```
      devtoolModuleFilenameTemplate: '[absolute-resource-path]',
      devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
```

Anyways, the bottom line is it looks like I may still need to configure source-maps (i.e. it isn't enabled out of the box). So, I'll read up more on the webpack documentation on how it works and to configure it.

**Comment by ricardolpd** [comment]
hey guys, i am having the same problem, i have put in my config, an output filename, and path, but it seems to ignore it, where do compiled the files end up in??

**Comment by NoiSek** [comment]
The description is a little misleading in this case, Mocha handles sourcemaps insofar as the communication from Webpack's built and already-sourcemapped files < -- > Mocha from what I can tell. To do this, you would normally have to include and initialize Mocha with a plugin.

Use `devtool: 'cheap-module-source-map'` and you'll see what you're after.

**Comment by jeffgran** [comment]
Just spent 4 hours on this. In my case, it turned out that we had a `mocha-webpack.opts` file in the root of the js project, which I guess takes effect by default, and there was a line 

```--require source-map-support/register``` 

in it. I **removed that line and it fixed my source maps**, although they are still prefixed with the `.tmp` path like `.tmp/mocha-webpack/1523062282715/spec/components/foo/foo_spec.jsx`.

I "fixed" that by changing my output section in my `webpack.config-test.js` like this: 

```
  output: {
    devtoolFallbackModuleFilenameTemplate: ' -- [absolute-resource-path]?[hash]',
    devtoolModuleFilenameTemplate: ' -- [absolute-resource-path]',
  },
```
so now the lines in my stack traces look like:

```
at Context.<anonymous> (.tmp/mocha-webpack/1523062282715/ -- spec/components/foo/foo_spec.jsx:72:1)
```

so at least my "go to this file path" takes me to the right file now, since there's a space separating the good part from the tmp part.

Isn't javascript awesome? /s
