### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by michaelbrawn** [zinserjan/mocha-webpack#234]
Webpack 4 isn't currently supported. 

https://github.com/zinserjan/mocha-webpack/pull/225 adds support for webpack 4.

**Comment by hyrumwhite** [comment]
Webpack v4 is also not working for me. I couldn't get webpack to run under v4, downgraded to v3 with no configuration changes and it worked. Here's the output for the v4 run:
![image](https://user-images.githubusercontent.com/4398358/38639841-af264970-3d8f-11e8-8e11-d32e3131d789.png)
If I turn off warnings, it just says: WEBPACK Compiled Successfully.

**Comment by rmuchall** [comment]
@zinserjan 
Would it be possible to get #225 merged and released as mocha-webpack@next so that we can use it to upgrade to Webpack 4?

Right now mocha-webpack is the only dependency we have in our project that does not support Webpack 4. Many thanks for your consideration :)

**Comment by thomasmichaelwallace** [comment]
n.b. I've added a branch to my #225 PR that includes the built version of mocha-webpack with the fix in.

So if you want a working version, you can temporarily use the package:

`"mocha-webpack": "https://github.com/thomasmichaelwallace/mocha-webpack#build",`

However this _isn't_ a fork, and I won't be maintaining it after the issue is closed.

**Comment by michaelbrawn** [comment]
Thanks @thomasmichaelwallace! I'm in a position to wait for the PR for now, but I'm sure others can use that.
Would love if this could be fixed and released officially.

**Comment by kamilwylegala** [comment]
@zinserjan 

Is there any chance to release version `2.0.0-beta.0` to npm? According to PR https://github.com/zinserjan/mocha-webpack/pull/211 support for webpack 4 is available.

**Comment by rmuchall** [comment]
Is this package still being maintained?

**Comment by serut** [comment]
We have an issue with `2.0.0-beta.0` : 
```
 WEBPACK  Compiled successfully in 91543ms

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

/home/lmieulet/CS/rs-frontend/webapp/.tmp/mocha-webpack/1532524466689/css/styles.css:11
small, strike, strong, sub, sup, tt, var,
                                     ^^^

SyntaxError: Unexpected token var
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha-webpack/lib/util/registerRequireHook.js:148:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha/lib/mocha.js:576:10)
    at /home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha-webpack/lib/runner/TestRunner.js:191:27
    at /home/lmieulet/CS/rs-frontend/webapp/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/lmieulet/CS/rs-frontend/webapp/node_modules/tapable/lib/HookCodeFactory.js:24:12),<anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/lmieulet/CS/rs-frontend/webapp/node_modules/tapable/lib/Hook.js:35:21)
    at emitRecords.err (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:372:39)
    at emitAssets.err (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:358:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/lmieulet/CS/rs-frontend/webapp/node_modules/tapable/lib/HookCodeFactory.js:24:12),<anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/lmieulet/CS/rs-frontend/webapp/node_modules/tapable/lib/Hook.js:35:21)
    at asyncLib.forEach.err (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:355:27)
    at done (/home/lmieulet/CS/rs-frontend/webapp/node_modules/neo-async/async.js:2854:11)
    at /home/lmieulet/CS/rs-frontend/webapp/node_modules/neo-async/async.js:2805:7
    at MemoryFileSystem.writeFile (/home/lmieulet/CS/rs-frontend/webapp/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/lmieulet/CS/rs-frontend/webapp/node_modules/webpack/lib/Compiler.js:339:29)
    at Immediate._onImmediate (/home/lmieulet/CS/rs-frontend/webapp/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

npm ERR! Test failed.  See above for more details.
```
Looks like it tries to run the CSS as some Javascript file. Maybe that's related to `MiniCssExtractPlugin` but `webpack-dev-server` is running fine.. Does someone have the same issue ?

Here are changes I've made for migrating from Webpack 3 to Webpack 4 :  
![changes](https://user-images.githubusercontent.com/2767218/43205291-521cc9f2-9023-11e8-82fc-5fb0e3e00a29.png)

**Comment by serut** [comment]
Ok I found a workaround.
```
          use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
          ],
```
becomes
```
          use: mode !== 'test' ? [
            MiniCssExtractPlugin.loader,
            'css-loader',
          ] : ['css-loader'],
```

**Comment by markerikson** [comment]
Just now looking at upgrading our app to Webpack 4.  Any updates on the status if this?  Will the `next` tag work okay, or is #225 necessary?
