### ISSUE TITLE
Error when using `--watch` flag as documented

### ISSUE THREAD

**Issue by leegee** [zinserjan/mocha-webpack#298]
```bash
[pwa-shell 11:47:12] node -v
v8.14.0
[pwa-shell 11:47:14] mocha-webpack --watch ../ice-webelements/redux/bright-portal-actions/user-management.spec.js
------------ BUILDING ENV  development
------------ BUILDING: bright-portal ------------
Reading  ./env/development.env
  Added env var BRIGHT_PORTAL_URI_USERS_RETRIEVE = "http://localhost:3001/api/users/list"
  Added env var BRIGHT_PORTAL_URI_USER_CREATE = "http://localhost:3001/api/users/create"
  Added env var BRIGHT_PORTAL_URI_USER_UPDATE = "http://localhost:3001/api/users/update"
  Added env var BRIGHT_PORTAL_URI_SCOPES = "=http://localhost:3001/api/scopes"
  Added env var BRIGHT_PORTAL_URI_USER_AAA = "http://localhost:3001/api/users/roles"
------------ SHELL VERSION: 0.9.0 ------------
------------ APP VERSION: 1.0.8 ------------
TypeError: compiler.constructor.Watching is not a constructor
    at createWatcher (/Users/lee.goddard/src/pwa-shell/node_modules/mocha-webpack/lib/webpack/compiler/createWatchCompiler.js:26:12)
    at Object.watch (/Users/lee.goddard/src/pwa-shell/node_modules/mocha-webpack/lib/webpack/compiler/createWatchCompiler.js:33:25)
    at TestRunner.<anonymous> (/Users/lee.goddard/src/pwa-shell/node_modules/mocha-webpack/lib/runner/TestRunner.js:308:25)
    at eval (eval at processIncludes (/Users/lee.goddard/src/pwa-shell/node_modules/nodent-runtime/runtime.js:36:12), <anonymous>:3:4727)
    at <anonymous>
[pwa-shell 11:47:18]
```

**Comment by leegee** [comment]
Fixes it in an ugly way - I'm working with an older webpac if that's relevant:
```
  const path = require('path');
  const Watching = require(path.resolve(__dirname, '../../../../webpack/lib/Watching'));
  let createWatcher = function createWatcher() {
    return new Watching(compiler, watchOptions, noop);
  };
```
