### ISSUE TITLE
 RUNTIME EXCEPTION  Exception occurred while loading your tests Cannot read property 'assign'

### ISSUE THREAD

**Issue by suwdus** [zinserjan/mocha-webpack#303]
I've been trying to run mocha tests on angular project and I can't seem to get past this runtime exception which occurs.

Versions:

Mocha 5.0.x
Mocha-Webpack 1.0.x
Types-Mocha 2.2.x

Stack trace:

MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests

TypeError: Cannot read property 'assign' of undefined
    at getAssign (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/src/util/assign.ts:17:22)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/src/util/assign.ts:20:23)
    at Module._compile (module.js:653:30)
    at Module.replacementCompile (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/ts-node/src/index.ts:431:14)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at _module2.default._extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/src/observable/dom/WebSocketSubject.ts:11:1)
    at Module._compile (module.js:653:30)
    at Module.replacementCompile (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/ts-node/src/index.ts:431:14)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at _module2.default._extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/src/observable/dom/webSocket.ts:1:1)
    at Module._compile (module.js:653:30)
    at Module.replacementCompile (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/ts-node/src/index.ts:431:14)
    at /local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at _module2.default._extensions.(anonymous function) (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/mocha-webpack/lib/util/registerRequireHook.js:140:62)
    at Object.<anonymous> (/local/home/turnerpt/workspaces/RoBO_Code/src/ArrisDomeKatalWebsite/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

Any clues?

**Comment by larixer** [comment]
@suwdus  This project is no longer maintained, we didn't hear from the author since May 2018. We are maintaining the fork here:
https://github.com/sysgears/mochapack
Feel free to try it and create the issue there if you will still have this problem.
