### ISSUE TITLE
 WEBPACK  Failed to compile with 1 error  TypeError: mocha.useColors is not a function 

### ISSUE THREAD

**Issue by Neha8482** [zinserjan/mocha-webpack#329]
Can anyone please help me with this

 WEBPACK  Failed to compile with 1 error(s)

TypeError: mocha.useColors is not a function
    at configureMocha (C:\Users\dell\AppData\Roaming\npm\node_modules\mocha-webpack\lib\runner\configureMocha.js:34:9)
    at TestRunner.prepareMocha (C:\Users\dell\AppData\Roaming\npm\node_modules\mocha-webpack\lib\runner\TestRunner.js:139:48)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\mocha-webpack\lib\runner\TestRunner.js:193:36
    at C:\Users\dell\AppData\Roaming\npm\node_modules\mocha-webpack\lib\webpack\compiler\registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:298:10
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:464:33
    at MemoryFileSystem.writeFile (C:\Users\dell\AppData\Roaming\npm\node_modules\mocha-webpack\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)

**Comment by abnovak** [comment]
I believe this has to do with Mocha deprecating some functions. Is this project dead? Or do we think there could be updates?

**Comment by larixer** [comment]
@Neha8482 @abnovak
`mocha-webpack` has no activity since May, 2018. I maintain a fork, named `mochapack`, since March 2019, here:
https://github.com/sysgears/mochapack
