### ISSUE TITLE
Strange failure

### ISSUE THREAD

**Issue by miguel-guedes** [zinserjan/mocha-webpack#43]
I'm getting a very strange failure whenever I attempt to run tests in node
environment.  The tests run fine in the browser though (using a slightly different configuration).  

I created a `test` script in `package.json` like so:
`"test": "mocha-webpack --colors --webpack-config webpack.config-test.js \"test/start.js\""`

`webpack.config-test.js` contains the following:

```javascript
var webpack = require("webpack");
var nodeExternals = require("webpack-node-externals");

module.exports = {
  target: "node",
  externals: [nodeExternals()],
  module: {
    preLoaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: "eslint" }
    ],
    loaders: [
      {
        test: /.js$/,
        loader: "babel",
        exclude: /node_modules/,
        query: {
          presets: ["es2015"],
          cacheDirectory: true
        }
      },
      { test: /\.json$/, loader: "json" },
      { test: /\.css$/, loader: "css" },
      { test: /\.html$/, loader: "dom!html" },
    ]
  },
  plugins: [
    new webpack.DefinePlugin({PRODUCTION: false,
                              BROWSER: false}),
  ],
  devtool: "source-map"
};
```
Whenever I run `npm test`, the following very strange output is produced:

```sh
$ npm test
> html-highlighter@0.1.3 test /home/miguelg/work/html-highlighter
> mocha-webpack --colors --webpack-config webpack.config-test.js "test/start.js"


WARNING in ./~/mocha-loader/EnhancedMocha.js
Critical dependencies:
29:24-37 the request of a dependency is an expression
 @ ./~/mocha-loader/EnhancedMocha.js 29:24-37

WARNING in ./~/mocha-loader/README.md
Module parse failed: /home/miguelg/work/html-highlighter/node_modules/mocha-loader/README.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/miguelg/work/html-highlighter/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/miguelg/work/html-highlighter/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/miguelg/work/html-highlighter/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/miguelg/work/html-highlighter/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/miguelg/work/html-highlighter/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/miguelg/work/html-highlighter/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/miguelg/work/html-highlighter/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/miguelg/work/html-highlighter/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./~/mocha-loader ^\.\/.*$




  0 passing (0ms)

  1) fix test errors

  0 passing (4ms)
  1 failing

  1)  fix test errors:
     Error: Cannot find module '!!/home/miguelg/work/html-highlighter/node_modules/babel-loader/index.js?{"presets":["es2015"],"cacheDirectory":true}!/home/miguelg/work/html-highlighter/node_modules/eslint-loader/index.js!/home/miguelg/work/html-highlighter/src/htmlhighlighter_test.js'.
      at .tmp/mocha-webpack/start.js:182:42
      at webpackContextResolve (.tmp/mocha-webpack/start.js:182:90)
      at webpackContext (.tmp/mocha-webpack/start.js:179:30)
      at Mocha.EnhancedMocha.loadFiles (.tmp/mocha-webpack/start.js:119:48)
      at Mocha.EnhancedMocha.watch (.tmp/mocha-webpack/start.js:139:8)
      at Object.<anonymous> (.tmp/mocha-webpack/start.js:85:8)
      at __webpack_require__ (.tmp/mocha-webpack/start.js:20:30)
      at webpackContext (.tmp/mocha-webpack/start.js:65:10)
      at Array.forEach (native)
      at Object.map../htmlhighlighter_test.js (.tmp/mocha-webpack/start.js:55:17)
      at __webpack_require__ (.tmp/mocha-webpack/start.js:20:30)
      at .tmp/mocha-webpack/start.js:40:18
      at Object.<anonymous> (.tmp/mocha-webpack/start.js:43:10)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at node_modules/mocha-webpack/lib/cli/runner.js:59:11
      at Compiler.<anonymous> (node_modules/mocha-webpack/lib/webpack/createCompiler.js:76:7)
      at Compiler.applyPlugins (node_modules/tapable/lib/Tapable.js:26:37)
      at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:193:12)
      at Compiler.emitRecords (node_modules/webpack/lib/Compiler.js:282:37)
      at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:187:11)
      at node_modules/webpack/lib/Compiler.js:275:11
      at Compiler.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:60:69)
      at Compiler.afterEmit (node_modules/webpack/lib/Compiler.js:272:8)
      at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:267:14)
      at node_modules/async/lib/async.js:52:16
      at done (node_modules/async/lib/async.js:246:17)
      at node_modules/async/lib/async.js:44:16
      at node_modules/graceful-fs/graceful-fs.js:43:10
      at FSReqWrap.oncomplete (fs.js:82:15)



npm ERR! Test failed.  See above for more details.
```

I'm baffled.  Notice the warning on the `README.md` file and the wrong tests
being run ("fix test errors").

Any thoughts as to what is happening?

**Comment by miguel-guedes** [comment]
Not related to mocha-webpack.  Apologies.
