### ISSUE TITLE
CSS and SCSS problems

### ISSUE THREAD

**Issue by jordond** [zinserjan/mocha-webpack#5]
I've spent far too long looking at this problem myself, and need some help.

In my tests I am importing an angular component that imports some CSS files from node_modules, and some SCSS from the same directory.

Like so:
```javascript
import 'font-awesome/css/font-awesome.css';
import './main.scss';
```

If I run mocha-webpack I get this:

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/beep/dev/test/.tmp/mocha-webpack/f881bff69e3f75b90d6
1f9ea811cbdc0/external "font-awesome/css/font-awesome.css":1:1)
```

If I comment out the node_modules css and try it with the SCSS file I get:

```
/home/beep/dev/test/node_modules/style-loader/addStyles.js:31
        if (typeof options.singleton === "undefined") options.singleton = isOldIE();
^
TypeError: Cannot read property 'toLowerCase' of undefined
    a t/home/beep/dev/test/node_modules/style-loader/addStyles.js:14:1
    at /home/beep/dev/test/node_modules/style-loader/addStyles.js:9:1
    at module.exports (/home/beep/dev/test/node_modules/style-loader/addStyles.js:31:
1)
    at Object.<anonymous> (/home/beep/dev/test/src/client/main/main.scss?caf6:7:1)
```

My webpack config is: 

```javascript
{
  output: {
    devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
  },
  entry: {},
  target: 'node',
  externals: [nodeExternals()],
  devtool: 'cheap-module-source-map',
  module: {
      loaders: [
        { test: /\.tpl.html$/, loader: 'ngtemplate?relativeTo=' + (path.resolve(__dirname, './src/client')) + '/!html-loader' },
        { test: /\.css$/, loader: 'style!css' },
        { test: /\.scss$/, loader: 'style-loader!css-loader!autoprefixer-loader!sass-loader' },
        { test: /\.js$/, exclude: /(node_modules)/, loader: 'ng-annotate!babel' },
        { test: /\.(jpe|jpg|woff|woff2|eot|ttf|svg)(\?.*$|$)/, loader: 'file?name=fonts/[name].[ext]' }
      ]
    }
}
```

I guess I just need some way of forcing webpack to ignore html, css, scss, etc.  But I am unsure on how to do that.

**Comment by texttechne** [comment]
`Style-loader` doesn't support rendering on node. You could use the [`null-loader`](https://github.com/webpack/null-loader) to skip loading style files:
```
{ test: /\.(s)?css$/, loader: 'null' }
```

**Comment by zinserjan** [comment]
Sorry for the delay.

There are two problems with your webpack config:

1. Like @texttechne mentioned, style-loader works only in a browser environment (depends on document). null-loader is the way to go to ignore your css files. If you wanna use css-modules in the future, you have to use `css-loader/locales` instead of `style-loader!css`.
2. nodeExternals() skips bundling your css files from node_modules into your bundle. That should be the reason why you get this `Unexpected token ILLEGAL` error. Use webpack-node-externals [whitelist ](https://github.com/liady/webpack-node-externals#optionswhitelist-)option to include this file into the bundle.

**Comment by jordond** [comment]
Thank you, this is what happens when you're up until 3 am trying to solve a problem.  I should have realized this sooner.

**Comment by chrisregner-com** [comment]
I think I'm having the same issue. The solution above doesn't work. I also note that I haven't actually used CSS modules but I plan to do so in this project

**CSS import**
```
import 'tachyons/css/tachyons.css'
```

**webpack.config.js**
```
import nodeExternals from 'webpack-node-externals'
import merge from 'webpack-merge'
import webpackCommonConfig from './webpack.common.babel'
import { resolve } from 'path'

const webpackTestConfig = {

  context: resolve(__dirname, '../app'),

  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      Components: resolve(__dirname, '../app/components/'),
    },
  },

  module: {
    rules: [
      { loader: 'babel-loader', test: /\.jsx?$/, exclude: /node_modules/ },
      {
        loader: 'eslint-loader',

        // lint only spec files as the build files will be linted upon bundling
        test: /\.spec\.jsx?$/,

        exclude: /node_modules/,
        options: {
          configFile: '.eslintrc.test.js',
        },
      },

      // TODO: make it work
      {
        loader: 'css-loader/locals',
        test: /\.css$/,
        options: {
          modules: true,
          importLoaders: 1,
        },
      },
    ],
  },

  // in order to ignore built-in modules like path, fs, etc.
  target: 'node',

  // in order to ignore all modules in node_modules folder
  externals: [nodeExternals({
    // whitelist css libraries
    whitelist: ['tachyons'],
  })],
}

export default webpackTestConfig
```

**What the console says:**
```
C:\my-proj-dir\node_modules\tachyons\css\tachyons.css:34
html { font-family: sans-serif; /* 1 */ line-height: 1.15; /* 2 */ -ms-text-size-adjust: 100%; /* 3 */ -webkit-text-size-adjust: 100%; /* 3 */ }
     ^
SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\my-proj-dir\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:270:18)
    at __webpack_require__ (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:20:30)
    at Object.defineProperty.value (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:170:84)
    at __webpack_require__ (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:20:30)
    at Object.defineProperty.value (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:203:63)
    at __webpack_require__ (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:20:30)
    at webpackContext (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:127:9)
    at Array.forEach (native)
    at Object.<anonymous> (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:160:10)
    at __webpack_require__ (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:20:30)
    at C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:66:18
    at Object.<anonymous> (C:/my-proj-dir/.tmp/mocha-webpack/28ce5d28ff20d16d8403d2e0b78abac3/28ce5d28ff20d16d8403d2e0b78abac3-output.js:1:10)
    at Module._compile (module.js:570:32)
    at loader (C:\my-proj-dir\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\my-proj-dir\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\my-proj-dir\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\my-proj-dir\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (C:\my-proj-dir\node_modules\mocha\lib\mocha.js:495:10)
    at runMocha (C:\my-proj-dir\node_modules\mocha-webpack\lib\cli\runner.js:86:27)
    at C:\my-proj-dir\node_modules\mocha-webpack\lib\cli\runner.js:114:7
    at Compiler.<anonymous> (C:\my-proj-dir\node_modules\mocha-webpack\lib\webpack\createCompiler.js:78:7)
    at Compiler.applyPlugins (C:\my-proj-dir\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:98:16)
    at C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:73:18
    at Compiler.emitRecords (C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:367:37)
    at C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:56:19
    at C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:360:11
    at next (C:\my-proj-dir\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.compiler.plugin (C:\my-proj-dir\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\my-proj-dir\node_modules\tapable\lib\Tapable.js:158:13)
    at Compiler.afterEmit (C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:357:8)
    at Compiler.<anonymous> (C:\my-proj-dir\node_modules\webpack\lib\Compiler.js:352:14)
    at C:\my-proj-dir\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\my-proj-dir\node_modules\async\dist\async.js:998:13)
    at C:\my-proj-dir\node_modules\async\dist\async.js:906:16
    at C:\my-proj-dir\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by chrisregner-com** [comment]
Got it finally working after all those hours.

Here's what worked. I've used[`css-modules-require-hook`](https://github.com/css-modules/css-modules-require-hook).

**Here's how my final `webpack` config file looked:**
```
import nodeExternals from 'webpack-node-externals'
import merge from 'webpack-merge'
import webpackCommonConfig from './webpack.common.babel'
import { resolve } from 'path'

const webpackTestConfig = {

  context: resolve(__dirname, '../app'),

  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      Components: resolve(__dirname, '../app/components/'),
    },
  },

  module: {
    rules: [
      { loader: 'babel-loader', test: /\.jsx?$/, exclude: /node_modules/ },
      {
        loader: 'eslint-loader',

        // lint only spec files as the build files will be linted upon bundling
        test: /\.spec\.jsx?$/,

        exclude: /node_modules/,
        options: {
          configFile: '.eslintrc.test.js',
        },
      },

      // TODO: make it work
      {
        loader: 'css-loader/locals',
        test: /\.css$/,
        options: {
          modules: true,
          // removed importLoaders: 1, found out I didn't need it
          localIdentName: '[local]',
        },
      },
    ],
  },

  // in order to ignore built-in modules like path, fs, etc.
  target: 'node',

  // in order to ignore all modules in node_modules folder
  externals: [nodeExternals({
    // whitelist css libraries
    whitelist: ['tachyons'],
  })],
}

export default webpackTestConfig
```

`mocha-css-modules-setup-js`:
```
const hook = require('css-modules-require-hook')

hook({}) // the empty object is required for it to work

```

Finally, I've run the `css-module-require-hook` by adding `--require mocha-css-modules-setup.js` to my `mocha-webpack` script, which results to `mocha-webpack --require mocha-css-modules-setup.js`
