### ISSUE TITLE
Issue with style-loader

### ISSUE THREAD

**Issue by Robinfr** [zinserjan/mocha-webpack#52]
I have an issue with the style-loader when trying to run mocha-webpack in one of my projects:

```bash
/home/jan/workspace/repos/special_stuff/node_modules/style-loader/addStyles.js:31
	if (typeof options.singleton === "undefined") options.singleton = isOldIE();
^
ReferenceError: window is not defined
    at /home/jan/workspace/repos/special_stuff/node_modules/style-loader/addStyles.js:14:1
    at /home/jan/workspace/repos/special_stuff/node_modules/style-loader/addStyles.js:9:1
    at module.exports (/home/jan/workspace/repos/special_stuff/node_modules/style-loader/addStyles.js:31:1)
    at Object.<anonymous> (/home/jan/workspace/repos/special_stuff/modules/shared/styles/components/Menu.scss?22f3:7:1)
```

Here is my test config:

```js
var nodeExternals = require('webpack-node-externals');

module.exports = {
    module: {
        loaders: [
            { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader' },
            { test: /\.scss$/, loaders: ['style', 'css', 'sass'] },
            { test: /\.css$/, loaders: ['style', 'css'] },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'file?hash=sha512&digest=hex&name=[hash].[ext]',
                    'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
                ]
            },
            { test: /\.(otf|eot|svg|ttf|woff2?)/i, loader: require.resolve('url-loader') }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    output: {
        // sourcemap support for IntelliJ/Webstorm
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    },
    target: 'node', // in order to ignore built-in modules like path, fs, etc.
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
    devtool: "cheap-module-source-map" // faster than 'source-map'
};
```

Any clue on why I'm getting this error? It's working fine in a different project where I am using the exact same configuration..

Any help would be highly appreciated.

**Comment by zinserjan** [comment]
`style-loader` works only in a browser environment. There is no window in node.

If this works in another project for you, there are two possibilities:
* there is no file referenced in tests with a css import
* there is a mock browser environment like jsdom

Seems like you are not using CSS-Modules, so you can simply replace all CSS loaders with [null-loader](https://github.com/webpack/null-loader).

e.g.
```js
var nodeExternals = require('webpack-node-externals');

module.exports = {
    module: {
        loaders: [
            { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader' },
            { test: /\.scss$/, loader: 'null' },
            { test: /\.css$/, loader: 'null' },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'file?hash=sha512&digest=hex&name=[hash].[ext]',
                    'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
                ]
            },
            { test: /\.(otf|eot|svg|ttf|woff2?)/i, loader: require.resolve('url-loader') }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.jsx']
    },
    output: {
        // sourcemap support for IntelliJ/Webstorm
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    },
    target: 'node', // in order to ignore built-in modules like path, fs, etc.
    externals: [nodeExternals()], // in order to ignore all modules in node_modules folder
    devtool: "cheap-module-source-map" // faster than 'source-map'
};
```

**Comment by Robinfr** [comment]
@zinserjan yeah that works. You were correct that I was using a mock environment in the other project. Something I didn't realize when I was comparing them.. Thanks.
