### ISSUE TITLE
Cannot integrate with jsdom

### ISSUE THREAD

**Issue by batusai513** [zinserjan/mocha-webpack#6]
when i try to add jsdom with the basic boilerplate in the test-setup.js file
```js
global.document = require('jsdom').jsdom('<body><div id="root"></div></body>');
global.window = document.defaultView;
global.navigator = window.navigator;
```
and i run npm test it trows some errors 
```bash
WARNING in ./~/jsdom/lib/jsdom/utils.js
Module not found: Error: Cannot resolve module 'canvas' in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom
resolve module canvas in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom
  looking for modules in /Users/wardrakus/projects/react-boilerplate/client
    /Users/wardrakus/projects/react-boilerplate/client/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/client
      resolve file
        /Users/wardrakus/projects/react-boilerplate/client/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/client/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules
    /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules
      resolve file
        /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/react-boilerplate/node_modules
    /Users/wardrakus/projects/react-boilerplate/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/react-boilerplate/node_modules
      resolve file
        /Users/wardrakus/projects/react-boilerplate/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/react-boilerplate/node_modules/canvas.js doesn't exist
  looking for modules in /Users/wardrakus/projects/node_modules
    /Users/wardrakus/projects/node_modules/canvas doesn't exist (module as directory)
    resolve 'file' canvas in /Users/wardrakus/projects/node_modules
      resolve file
        /Users/wardrakus/projects/node_modules/canvas doesn't exist
        /Users/wardrakus/projects/node_modules/canvas.js doesn't exist
[/Users/wardrakus/projects/react-boilerplate/client/canvas]
[/Users/wardrakus/projects/react-boilerplate/client/canvas]
[/Users/wardrakus/projects/react-boilerplate/client/canvas.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/node_modules/canvas.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas]
[/Users/wardrakus/projects/react-boilerplate/node_modules/canvas.js]
[/Users/wardrakus/projects/node_modules/canvas]
[/Users/wardrakus/projects/node_modules/canvas]
[/Users/wardrakus/projects/node_modules/canvas.js]
 @ ./~/jsdom/lib/jsdom/utils.js 343:19-36

WARNING in ./~/jsdom/lib/jsdom/living/xmlhttprequest.js
Critical dependencies:
19:23-30 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/jsdom/lib/jsdom/living/xmlhttprequest.js 19:23-30
WARNING in ./~/jsdom/lib/jsdom/living/window/History.idl                                                                                                              [12/1355]
Module parse failed: /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/window/History.idl The keyword 'enum' is reserved (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: The keyword 'enum' is reserved (1:0)
    at Parser.pp.raise (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:918:13)
    at Parser.pp.parseIdent (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:669:203)
    at Parser.pp.parseExprAtom (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:283:21)
    at Parser.pp.parseExprSubscripts (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1750:23)
    at Parser.pp.parseTopLevel (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1645:21)
    at Parser.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:1613:17)
    at Object.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/acorn/dist/acorn.js:880:44)
    at Parser.parse (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/wardrakus/projects/react-boilerplate/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/wardrakus/projects/react-boilerplate/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/wardrakus/projects/react-boilerplate/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./~/jsdom/lib/jsdom/living ^\.\/.*$
ERROR in ./~/jsdom/lib/jsdom/living/generated/DOMPointReadOnly.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../nodes/DOMPointReadOnly-impl.js in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated
resolve file
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js doesn't exist
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js.js doesn't exist
resolve directory
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js doesn't exist (directory default file)
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js/package.json doesn't exist (directory description file)
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/nodes/DOMPointReadOnly-impl.js.js]
 @ ./~/jsdom/lib/jsdom/living/generated/DOMPointReadOnly.js 135:13-57

ERROR in ./~/jsdom/lib/jsdom/living/generated/ScrollIntoViewOptions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./ScrollOptions in /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated
resolve file
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions doesn't exist
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions.js doesn't exist
resolve directory
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions doesn't exist (directory default file)
  /Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions/package.json doesn't exist (directory description file)
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions]
[/Users/wardrakus/projects/react-boilerplate/node_modules/jsdom/lib/jsdom/living/generated/ScrollOptions.js]
 @ ./~/jsdom/lib/jsdom/living/generated/ScrollIntoViewOptions.js 6:22-48
```
how do you run tests that needs the actual DOM?, it is posible to add jsdom to this setup?

thanks

**Comment by zinserjan** [comment]
Can you provide a repo or at least your webpack config?

Looks like webpack can't bundle `jsdom`. Ignore your node_modules and try it again.

**Comment by batusai513** [comment]
hi @zinserjan, i can't post the repo but i'll post the conf files that i'm using
`webpack.config.test.js`
```js
const path = require('path')
const webpack = require('webpack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const extractCSS = new ExtractTextPlugin('vendor.css', {
  allChunks: true
})

module.exports = {
  entry: {
    test: [
      'sinon/pkg/sinon.js'
    ],
    client: [path.resolve(__dirname, './app/main.js')]
  },
  externals: {
    jsdom: 'window',
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
    'react/addons': true,
    'text-encoding': 'window'
  },
  module: {
    noParse: [
        /\/sinon\.js/
    ],
    loaders: [
      {
        test: /\.scss$/,
        loaders: [
          'css/locals?modules&importLoaders=1' +
            '&localIdentName=[path][local]__[hash:base64:5]',
          'sass'
        ]
      },
      {
        test: /sinon\/pkg\/sinon\.js/,
        loader: 'imports?define=>false,require=>false'
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['babel']
      }, {
        test: /\.css$/,
        loader: extractCSS.extract('css')
      }, {
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg)$/,
        loader: 'url-loader?limit=30000&name=[name]-[hash].[ext]'
      }, {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: '[name].js'
  },
  plugins: [
    extractCSS,
    new webpack.optimize.OccurenceOrderPlugin()
  ],
  resolve: {
    alias: {
      sinon: 'sinon/pkg/sinon.js',
      'cheerio': 'cheerio/lib/cheerio'
    },
    root: path.resolve(__dirname, './app'),
    extensions: ['', '.js']
  },
  target: 'node'
}
```
`test/setup`
```js
require("mock-local-storage");
// require('sinon-as-promised');
var chai = require('chai');
const chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

global.document = require('jsdom').jsdom('<body><div id="root"></div></body>');
global.window = document.defaultView;
global.navigator = window.navigator;
```
`mocha-webpack-opts`
```js
--include test/setup
--colors
--reporter spec
--webpack-config webpack.config.test.js
--recursive
test/**/*.spec.js
```
```js
{
"test:webpack": "NODE_ENV=test ./node_modules/.bin/mocha-webpack"
}
```

**Comment by zinserjan** [comment]
Seems that you are trying to use a client side webpack config for testing with node?

The main problem is that webpack isn't able to bundle all kinds of node_modules.
Replace your externals block with the webpack-node-externals plugin and it should work.

I modified your config a bit:
* replaced externals config with externals plugin --> jsdom should work now
* removed entry & output --> will be overridden by mocha-webpack
* removed sinon imports loader (whats the reason for that? sinon via npm is commonjs compatible)
* removed OccurenceOrderPlugin --> size doesn't matter
* replaced css loader with null loader

```javascript
const path = require('path')
const webpack = require('webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  externals: [nodeExternals()],
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: [
          'css/locals?modules&importLoaders=1' +
            '&localIdentName=[path][local]__[hash:base64:5]',
          'sass'
        ]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['babel']
      }, {
        test: /\.css$/,
        loader: 'null-loader'
      }, {
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg)$/,
        loader: 'url-loader?limit=30000&name=[name]-[hash].[ext]'
      }, {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  plugins: [],
  resolve: {
    alias: {
      sinon: 'sinon/pkg/sinon.js',
      'cheerio': 'cheerio/lib/cheerio'
    },
    root: path.resolve(__dirname, './app'),
    extensions: ['', '.js']
  },
  target: 'node'
}
```

**Comment by batusai513** [comment]
@zinserjan thank you for your help, it is working as expected, i'll close this issue.

Thanks again 👍
